### PR TITLE
a few changes

### PR DESCRIPTION
**Pull request by crazii**
Hi, I'd like to merge my mod, there're some changes made:

**1.jpeg format for flyers**

**2.custom buttons from mameplus , kind of a hack for MAME.**
make option: make USE_CUSTOM_BUTTON=1

**3.Simplified Chinese language.**
This is for MAMEUI, win32 front end, not MAME itself, since MAME already contains many languages. I'm sure more languages can be added.
Now each language need to be built into separated executable. it is possible to support multi-language if build the .res file into multiple resource DLL and switch/select them on startup.

make option: make FRONTEND_LANG=CHS

### CODE REVIEW

**Comment by Robbbert** [comment]
No thanks.
I may use the jpeg code later on.

**Comment by crazii** [comment]
Okay, cool. What about the other codes? I hope that they can be built into mameui so that I don't need a custom build.

**Comment by Robbbert** [comment]
Added jpeg support for all pictures. Thanks.

The other changes:
- compile on vc / cygwin - no, i don't care about other environments
- add standard chinese - unlikely
- add custom multi-buttons - not at this stage but may revisit it.

**Comment by crazii** [comment]
cool.

**Pull request closed without merging**
